steps:
  - name: build-push-result
    dockerBuild:
      registry: docker.io
      dockerSecret: docker-io
      dockerfilePath: Dockerfile
      user: kkrampa
      imageName: example-voting-app-result
      tag: master
      contextPath: ./result
