steps:
  - name: build-push-result-test
    dockerBuild:
      registry: docker.io
      dockerSecret: docker-io
      user: kkrampa
      imageName: example-voting-app-result
      tags: 
      - "master-{{ ICE_GIT_COMMIT_SHA }}"
      contextPath: result
      dockerfilePath: result/Dockerfile
